### ISSUE TITLE
error on flutter build iOS

### ISSUE THREAD

**Issue by ChrisHanna** [Almoullim/background_location#11]
Hi All,

I'm getting the following error when trying to build for iOS.
  
[!] CocoaPods could not find compatible versions for pod
    "background_location":
      In Podfile:
        background_location (from `.symlinks/plugins/background_location/ios`)

**Comment by LOCKEDFILE** [comment]
you need to change iOS Deployment Target Version.
> [your old version] -> **iOS 10.0**

and you just  type `pod install`.

Then, it's working **PERFECTLY**.
