### ISSUE TITLE
Build fails while using flutter build apk but works fine for building appbundle

### ISSUE THREAD

**Issue by nandakumar5398** [Almoullim/background_location#110]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processReleaseResources'.               
> Android resource linking failed                                       
  Output:  /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml:53: error: attribute android:foregroundServiceType not found.
  error: failed processing manifest.                                    
                                                                        
  Command: /Users/nanda/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/8ba7fbc12b64b5c7a86b4cae4553a83a/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/nanda/Library/Android/sdk/platforms/android-28/android.jar\
          --manifest\                                                   
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/processed_res/release/processReleaseResources/out/resources-release.ap_\
          -R\                                                           
          @/Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/incremental/processReleaseResources/resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /Users/nanda/Developer/temp/background_location-master/example/build/app/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --proguard\                                                   
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/proguard-rules/release/aapt_rules.txt\
          --custom-package\                                             
          com.example.backgeound_location_example\                      
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/symbols/release/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
  Output:  /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml:53: AAPT: error: attribute android:foregroundServiceType not found.
                                                                        
  error: failed processing manifest.                                    
  Command: /Users/nanda/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/8ba7fbc12b64b5c7a86b4cae4553a83a/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/nanda/Library/Android/sdk/platforms/android-28/android.jar\
          --manifest\                                                   
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/processed_res/release/processReleaseResources/out/resources-release.ap_\
          -R\                                                           
          @/Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/incremental/processReleaseResources/resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /Users/nanda/Developer/temp/background_location-master/example/build/app/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --proguard\                                                   
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/proguard-rules/release/aapt_rules.txt\
          --custom-package\                                             
          com.example.backgeound_location_example\                      
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /Users/nanda/Developer/temp/background_location-master/example/build/app/intermediates/symbols/release/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 12s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      13.6s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...                        5ms
✓ `android/settings_aar.gradle` created successfully.
Building plugin background_location...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                 2,205ms

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'background_location'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin background_location could not be built due to the issue above.

**Comment by sepehr13494** [comment]
same issue here

**Comment by NickoftheSouth** [comment]
I got this to build by bumping up the compileSdkVersion in the plugin to 30

That is changing line 28 in `/android/build.gradle` to:

`compileSdkVersion 30`

**Comment by MoralCode** [comment]
the current master branch uses a compileSdkVersion of 30. Closing as completed
