### ISSUE TITLE
Getting Fatal Crash in Release Apk.

### ISSUE THREAD

**Issue by nicks258** [Almoullim/background_location#117]
Hi, Thanks for the wonderfull plugin but I was facing crash in release apk with logcat
`Activity com.shubbak.driver_load_app.MainActivity has leaked ServiceConnection com.almoullim.background_location.c@ac53a85 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.shubbak.driver_load_app.MainActivity has leaked ServiceConnection com.almoullim.background_location.c@ac53a85 that was originally bound here`
In debug mode its working fine. Please help.

**Comment by nicks258** [comment]
Any updates?

**Comment by Waguy02** [comment]
Any updates?

**Comment by sunqihui222** [comment]
me to

**Comment by MoralCode** [comment]
does this issue by chance happen to occur when terminating the app with an active foreground service? id o, this might be a duplicate of https://github.com/Almoullim/background_location/issues/7
