### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified

### ISSUE THREAD

**Issue by juliansteenbakker** [Almoullim/background_location#125]
As per title. Android 31 requires a different flag for https://github.com/Almoullim/background_location/blob/e53dbcb728178e002717d9b49c6371ce77da9d0c/android/src/main/kotlin/com/almoullim/background_location/LocationUpdatesService.kt#L62

**Comment by narendra02031997** [comment]
In the new update location update not working
and with version 0.6.0 app was crashing in android version 12
 so what i did open
 background_location/android/src/main/kotlin/com/almoullim/background_location/LocationUpdatesService.kt
 this file and edit replace line 62 with following
 val pendingIntent = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                PendingIntent.getActivity(this, 1, intent, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
            } else {
               PendingIntent.getActivity(this, 1, intent, PendingIntent.FLAG_UPDATE_CURRENT)
            }
version 0.6.0 is working in android version 12 after replacing this.
