### ISSUE TITLE
Redeclarations erros

### ISSUE THREAD

**Issue by ir4ever** [Almoullim/background_location#141]
You can help me?

Erros: 

e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.7.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (29, 7): Redeclaration: BackgroundLocationPlugin
e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.7.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationService.kt: (23, 7): Redeclaration: BackgroundLocationService
e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.7.0\android\src\main\kotlin\com\almoullim\background_location\LocationUpdatesService.kt: (15, 7): Redeclaration: LocationUpdatesService
e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.8.1\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (10, 7): Redeclaration: BackgroundLocationPlugin
e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.8.1\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationService.kt: (23, 7): Redeclaration: BackgroundLocationService
e: C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.8.1\android\src\main\kotlin\com\almoullim\background_location\LocationUpdatesService.kt: (18, 7): Redeclaration: LocationUpdatesService

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1

**********
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.22000.376], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2020.3)
[√] Connected device (4 available)

• No issues found!

**********
 compileSdkVersion 31
 minSdkVersion 21
 multiDexEnabled true
 targetSdkVersion 31

*********
Flutter 2.8.1 • channel stable •
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by nicks258** [comment]
Did you find any solution for this? @Raphael-Jose-Ferraro-IRForever  @Almoullim

**Comment by MoralCode** [comment]
Closing as the logs in the original description appear toindicate a conflict between multiple installed versions of the library on OP's machine - does not appear to be an issue with the library (and also an old/stale issue)
