### ISSUE TITLE
iOS 15.2 Tracking stops while in background

### ISSUE THREAD

**Issue by manjunathaVadhiraaju** [Almoullim/background_location#143]
i'm facing issue With iOS 15 when app goes to background and blue colour status bar appears and lock the device after few mins blue colour status bar disappears appears background service killed and app keeps in background.

**Comment by aea91** [comment]
> i'm facing issue With iOS 15 when app goes to background and blue colour status bar appears and lock the device after few mins blue colour status bar disappears appears background service killed and app keeps in background.

Hi,
Did you find a solution about getting a location on the background for iOS?

**Comment by KarinBerg** [comment]
Same here, any hints for this issue?
