### ISSUE TITLE
New override error appeared somehow

### ISSUE THREAD

**Issue by PaulMinguet** [Almoullim/background_location#146]
Hi,
I've been using your library for some time and today, it wouldn't compile anymore.
Every time I build my app, I get this error :

`e: flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.8.1\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationService.kt: (23, 1): Class 'BackgroundLocationService' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.8.1\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationService.kt: (221, 5): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
`
And I don't know if it comes from my code (because I didn't touch it for like a week and the library worked before that) or from the library.

Thanks

**Comment by caiobraga** [comment]
i have the same problem

**Comment by nicklbaert** [comment]
Me too

**Comment by PlutoHDDev** [comment]
Same here

**Comment by bambinoua** [comment]
It looks like `pub.dev` contains old version not one which is in git.
I've fixed this using:
```
dependency_overrides:
  background_location:
    git:
      url: https://github.com/Almoullim/background_location.git
      ref: master
```

**Comment by MoralCode** [comment]
Yep, this was resolved in https://github.com/Almoullim/background_location/pull/174 and is part of the tagged version 0.10.0. It is not yet on pub.dev though so you'll probably need to use the latest main branch for now.
