### ISSUE TITLE
background notification not showing on android 12 due to low notification importance

### ISSUE THREAD

**Issue by renehw** [Almoullim/background_location#147]
I noticed that the notification that the app is getting the location in the background is not showing by default on android 12, it is necessary to manually change the notification setting on the device to "Allow", is there a way to force the app notification to be "important"?

**Comment by MoralCode** [comment]
I suspect this may be part of the reason why so many people are creating issues relating to background stuff not working

**Comment by Almoullim** [comment]
fixed in https://github.com/Almoullim/background_location/commit/52ef3db3e572596bb0e879dc57aa201fe160143e version 0.12.0
