### ISSUE TITLE
No implementation found for method set_android_notification on channel in sdk 31

### ISSUE THREAD

**Issue by caiobraga** [Almoullim/background_location#148]
i was following the tutorial of the link: https://flutterrepos.com/lib/Almoullim-background_location
but after adding the lines: 

await BackgroundLocation.setAndroidNotification(
      title: "Notification title",
      message: "Notification message",
      icon: "@mipmap/ic_launcher",
    );
    await BackgroundLocation.setAndroidConfiguration(1000);
    BackgroundLocation.startLocationService(distanceFilter: 10);

to the initState function of my code i get the error:

No implementation found for method set_android_notification on channel com.almoullim.background_location/methods

**Comment by caiobraga** [comment]
i fix the error above bu running flutter run. But now i'am getting the error:  Class 'BackgroundLocationService' is not abstract and does not implement abstract member

**Comment by caiobraga** [comment]
I found the solution by forking the project here: https://github.com/caiobraga/background_location

**Comment by MoralCode** [comment]
> But now i'am getting the error: Class 'BackgroundLocationService' is not abstract and does not implement abstract member

This seems to be resolved in https://github.com/Almoullim/background_location/pull/174 and is part of the tagged version 0.10.0. It is not yet on pub.dev though so you'll probably need to use the latest main branch for now.

What was your resolution for the error in the issue description?

**Comment by Almoullim** [comment]
Pub dev have the latest version as of now
