### ISSUE TITLE
Crash when used with other plugin (WorkManager)

### ISSUE THREAD

**Issue by fvisticot** [Almoullim/background_location#15]
I would like to use this background_plugin in addition with the workmanager plugin.
Workmanager (https://pub.dev/packages/workmanager) needs to register a callback in an overloaded Android application

When started I get a crash:
 java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 7146): 	at com.almoullim.background_location.BackgroundLocationPlugin$Companion.registerWith(BackgroundLocationPlugin.kt:37)
E/AndroidRuntime( 7146): 	at com.almoullim.background_location.BackgroundLocationPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime( 7146): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:42)
E/AndroidRuntime( 7146):

**Comment by Almoullim** [comment]
Should be fixed with https://github.com/Almoullim/background_location/pull/13. Re-open if not.
