### ISSUE TITLE
❗ This repository has been de-facto orphaned/abandoned since October 2021

### ISSUE THREAD

**Issue by haukepribnow** [Almoullim/background_location#164]
### Situation
The [last commit of the original author of this project](https://github.com/Almoullim/background_location/commit/264acf539ee2388525d2916f1a33aa967ba1095c) is from October 2021 and [the last time the author seems to have added a comment](https://github.com/Almoullim/background_location/pull/135#issuecomment-1000804395) was in December 2021. Since then, the author does not seem to have been active here anymore.

### Complication
I've noticed that some good contributions have started to independently appear in various forks. As these contributions do not "flow back" into this repository, the development around this project starts to diverge. As such, it will become harder and harder to integrate & benefit from new contributions. 

### Solution
I've tried to bring especially relevant contributions together again and also repair/rewire the Git histories in my fork: https://github.com/haukepribnow/background_location

And to provide a new active central repository where the development can converge again, **I would volunteer to at least merge PRs for fixes & improvements while the original author stays inactive.** So feel free to raise PRs at: https://github.com/haukepribnow/background_location But please note: I will definitely not be able to provide any kind of support; I will only take care about incoming PRs & do not plan to do any bugfixing by myself. Be aware that I would only do this as a hobby, so I'm sorry for any looong delays in advance.

Once the original author returns, I'm more than happy to work together with them to integrate the changes back into their repository.

**Comment by Almoullim** [comment]
Hello @haukepribnow, I apologize for the long absence, I had just started a new job and had too many other things to focus on for a while. I should be able to be back to keep managing and updating this project. 

On the above note, I would love to add you as a collaborator on this repo if you would like to help with PR's and/or issues. Please let me know!

I'm closing this for now.

**Comment by haukepribnow** [comment]
Thanks a lot! Looking forward to support this project.
