### ISSUE TITLE
Use `Position` class from `geolocator_platform_interface` instead current `Location`.

### ISSUE THREAD

**Issue by bambinoua** [Almoullim/background_location#169]
I suggest to use `Position` class from [geolocator_platform_interface](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_platform_interface/lib/src/models/position.dart) instead currenly used `Location` class.

**Comment by MoralCode** [comment]
I'm relatively new to this codebase so maybe this is obvious from the code, but is there any particular reasoning behind this change
