### ISSUE TITLE
crashing the application after calling startLocationService even if permission is granted for location

### ISSUE THREAD

**Issue by vaimikpatel2908** [Almoullim/background_location#17]
onPressed: () {
            try {
              BackgroundLocation.checkPermissions().then((status) {
                // Check status here
                if (status == PermissionStatus.granted) {
                  BackgroundLocation.startLocationService();
                  BackgroundLocation.getLocationUpdates((location) {
                    print(location.latitude.toString() +
                        "-" +
                        location.longitude.toString());
                  });
                } else if (status == PermissionStatus.disabled ||
                    status == PermissionStatus.denied) {
                  BackgroundLocation.getPermissions(onGranted: () {
                    BackgroundLocation.startLocationService();
                    BackgroundLocation.getLocationUpdates((location) {
                      print("loaction:" +
                          location.latitude.toString() +
                          "-" +
                          location.longitude.toString());
                    });
                  }, onDenied: () {
                    BackgroundLocation?.stopLocationService();
                  });
                }
              });
            } catch (e) {
              print(e.toString());
            }
          },

**Comment by isaacME21** [comment]
You have to add this in the info.plist :
<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>

**Comment by isaacME21** [comment]
you have to add this in the info.plist 
`<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>`

**Comment by vaimikpatel2908** [comment]
I was tring on android device is there anything like this for android which I shoud include in manifest or somewhere else

**Comment by vaimikpatel2908** [comment]
I was trying on android device so it couldn't be an issue.

**Comment by Almoullim** [comment]
> I was tring on android device is there anything like this for android which I shoud include in manifest or somewhere else

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
