### ISSUE TITLE
Execution failed for task ':background_location:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by alpeshbrainstream** [Almoullim/background_location#177]
Execution failed for task ':background_location:compileReleaseKotlin'.
> Compilation error. See log for more details

i can resolved this issue for change kt file

**Comment by loushiano** [comment]
Hello, any updates on this? I am facing this issue.

**Comment by alpeshbrainstream** [comment]
> Hello, any updates on this? I am facing this issue.

> Please see this comment
https://github.com/Almoullim/background_location/issues/172#issuecomment-1398416138

**Comment by MoralCode** [comment]
This seems to be resolved in https://github.com/Almoullim/background_location/pull/183 and is part of the tagged version 0.10.0. It is not yet on pub.dev though so you'll probably need to use the latest main branch for now.
