### ISSUE TITLE
Conflict between BackgroundLocation.getLocationUpdates and FirebaseMessaging.onBackgroundMessage

### ISSUE THREAD

**Issue by SimonTellier** [Almoullim/background_location#182]
Hi,
I am working on exporting my application to Android. Everything I'm going to say next works fine on iOS.

I'm looking for a way to get both services working in the background. (BackgroundLocation.getLocationUpdates and FirebaseMessaging.onBackgroundMessage)
When I run both services in the background, I only have FirebaseMessaging.onBackgroundMessage working.

When I run only BackgroundLocation.getLocationUpdates, the service works fine.

I would like to run both at the same time. Do you have any idea what is going on?

**Comment by sokheangret** [comment]
Hi, I'm facing with this issue too. Are there any solution? Thanks.

**Comment by MoralCode** [comment]
Are there any associated logs that you see when you try to run both at the same time?

**Comment by MoralCode** [comment]
Closing as duplicate of https://github.com/Almoullim/background_location/issues/139
