### ISSUE TITLE
Flutter Android Version 3.0 Support

### ISSUE THREAD

**Issue by pkcell** [Almoullim/background_location#184]
It seems like this packages is not supported on Flutter version 3.0, specifically during android builds. The output received from android build:

`.pub-cache/hosted/pub.dev/background_location-0.8.1/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationService.kt: (23, 1): Class 'BackgroundLocationService' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/<myusername>/.pub-cache/hosted/pub.dev/background_location-0.8.1/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationService.kt: (221, 5): 'onRequestPermissionsResult' overrides nothing`

## Flutter Doctor:
`<myusername>@myusername-MBP bin % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!`

**Comment by Myzel394** [comment]
Did you find a solution @pkcell? It doesn't work on iOS too.

**Comment by MoralCode** [comment]
The issue described in the PR description has been resolved in #174 and is part of the tagged version 0.10.0. It is not yet on pub.dev though so you'll probably need to use the latest main branch for now.

**Comment by MoralCode** [comment]
@Myzel394 are you seeing the same error or a different one on iOS?

**Comment by Myzel394** [comment]
@MoralCode I switched to `background_fetch`, sorry

**Comment by MoralCode** [comment]
Closing because the originally reported issue is now resolved and not enough information was provided for the iOS issue to be able to differentiate it - if this iOS issue is identified in future, it should get its own new issue if one does not already exist
