### ISSUE TITLE
showing blue bar at the top of screen when app goes in background

### ISSUE THREAD

**Issue by Aadesh1803** [Almoullim/background_location#185]
is there any way to get location update but not show that blue bar at the top of screen in ios?

**Comment by Xsantosh** [comment]
You can't do that, IOS controls the blue bar and shows that. An application is accessing your current location in the background.

**Comment by MoralCode** [comment]
heres a source in case it helps:
> For apps with When In Use authorization, the system changes the appearance of the status bar when the app uses location services in the background.

https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator
