### ISSUE TITLE
Does not receive background updates in emulator.

### ISSUE THREAD

**Issue by frazboyz** [Almoullim/background_location#19]
The package does not seem to receive background updates on **Android** when the emulator's screen is off(I presume the off button on the emulator is simply just the screen being off and not the device).

The package, however, does work well if you have the screen on, the active app is google maps and the app is in the background.

**Comment by Almoullim** [comment]
@frazboyz I’m currently unable to check with your issue but I’ll try to get on it as soon as i can.

All i can do now is guess. Since, as you said, the app is working in the background, turning the screen off shouldn’t be any different, unless you maybe have something like a power save mode active which turns off background process. Or the phone is going into deep sleep mode while the screen is off.

**Comment by frazboyz** [comment]
Thanks for the response. I'm using the Android emulator and pressing the power button on the emulator ui.

I'll install the app on my physical device and see if it works and get back to you.

Cheers mate.

**Comment by Sly2024** [comment]
I have the same issue, both on the emulator and on my onplus 7.
When I put back the app in foreground, it's like all the background tasks are handled at once

**Comment by frazboyz** [comment]
@Sly2024 I think that is meant to happen, your app is not alive in the background, the android service is. So once your app is in the foreground/alive again, it receives the events.

**Comment by frazboyz** [comment]
@Almoullim When you get a chance, could you fire up the example app in this repository inside an Android emulator running Android 10, Google Pixel 3 with API v29. It didn't seem to work for me.

**Comment by frazboyz** [comment]
This seems to be a general limitation of Android 8+.

**Comment by Sly2024** [comment]
> 
> 
> @Sly2024 Very strange. @Sly2024... If you open google maps with your app in the background, you receive location updates.

Actually, I wanted to fire a notification when I get close to a location. So launching google maps is not an acceptable option for me.
I need to execute some basic code every time, not all at once when I put the app in foreground.
Considering what you said, I think this plugin will not work for me :( 
Does anyone know how I can do that?

**Comment by frazboyz** [comment]
@Sly2024 Geofencing is the perfect solution for you I believe. Basically you define an area of coordinates and Android will call your code when you reach that area.

**Comment by Almoullim** [comment]
https://github.com/Almoullim/background_location/commit/22d08f58a2c0b29807ce9f8f20bb7f488fa3acad this commit here must be whats causing this

**Comment by Almoullim** [comment]
https://github.com/Almoullim/background_location/commit/27f0ff0653a36b62e900ac27e28dd777f428c7b1 this seems to fix it, can you update and test it and let me know if the issue is still there?
