### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'background_location/background_location-Swift.h' file not found

### ISSUE THREAD

**Issue by fuyacho-takatsuji** [Almoullim/background_location#191]
Hi
i ran into the following error message when I did debug mode installi to iPhone8.
>>Running Xcode build..
>>Xcode build done.
>>Failed to build iOS app
>>Could not build the precompiled application for the device.
>>Lexical or Preprocessor Issue Xcode):'background_location/background_location-Swift.h' file not found
/Users/nakanokomotodaka/.pubcache/hosted/pub.dev/background_location-0.11.8/ios/Classes/BackgroundLocationPlugin.m:1:8

What I was doing is
> Android studio on MACOS 13.2, 
>Android Studio Dolphin | 2021.3.1 Patch 1
>  background_location: ^0.11.8

My app is getting location using background_location(This). Just gettijng location data worked fine on both iphone and android. I added googlemap and tried to install to iphone8, it failed with the error message above. Meanwhile It worked fine with Android.  Would you help?

Thanks,
T.Yokota

**Comment by MoralCode** [comment]
> I added googlemap and tried to install to iphone8, it failed with the error message above.

so youre saying theres a conflict with google maps somehow? how did you add google maps?

do you have a link to your source code (or if its not public, a repository with a minimal reproducible example) that I could run on my machine?

**Comment by fuyacho-takatsuji** [comment]
Hi MoralCode,
Thank you very much for your help. You guess adding GoogleMap causes some conflict,..., maybe it is what happened in my case. I checked internet and found similar error happened with geolocation. I guess  'background_location-Swift.h' is temporally  created by Android Studio, but for my case Android Studio could not handle it for some reason.

I placed zip file as
http://www.boatgps.sakura.ne.jp/GPSback.zip.

Please download by putting this address in browser address input.  

Thanks,
T.Yokota

**Comment by MoralCode** [comment]
> I guess 'background_location-Swift.h' is temporally created by Android Studio, but for my case Android Studio could not handle it for some reason.

are you trying to generate an iOS app in android studio? the name of that file - and the mention of Xcode in your title indicates to me that these issues are happening on a mac/on the iOS platform
