### ISSUE TITLE
Bug in Background

### ISSUE THREAD

**Issue by Abolfazlnezami2000** [Almoullim/background_location#213]
When I killed the app, everything stopped (notification and getLocationUpdates). how do I run in the background?
Do we need [background_fetch](https://pub.dev/packages/background_fetch) to run in the background?

**Comment by rajeev1982** [comment]
I am facing the same issue. As soon as I close the app, location updates stop, notification disappears. Any solution so far?

**Comment by MoralCode** [comment]
i believe a fork was made to address this in #207. Unfortunately this repo is seeking contributors (per #188) and I don't have the ability to singlehandedly do all of the things that would be needed to keep this repository in a high-quality/well-maintained state.

**Comment by MoralCode** [comment]
@Abolfazlnezami2000 @rajeev1982 if you could verify that the linked PR (#208) works for you, that would help me verify that the PR is good and can be merged (as I'm unable to test it directly myself)
