### ISSUE TITLE
Conflict between BackgroundLocation.getLocationUpdates and FirebaseMessaging.onBackgroundMessage

### ISSUE THREAD

**Issue by NANAIPRM** [Almoullim/background_location#215]
from title above, Can someone help me to  solve this problem.

**Comment by HeeJohn** [comment]
> from title above, Can someone help me to solve this problem.

I am facing the same issue at the moment. Did you figure it out somehow?

**Comment by NANAIPRM** [comment]
Currently, I use the [location](https://pub.dev/packages/location) library instead of the [background_location](https://pub.dev/packages/background_location) library. They seem to have similar functionality.

**Comment by HeeJohn** [comment]
Thanks!
