### ISSUE TITLE
Namespace not specified in the latest version of background_location

### ISSUE THREAD

**Issue by ClevertonZarelli** [Almoullim/background_location#219]
Hello,

I'm encountering an issue with the latest version of the background_location package. When I try to build my Flutter project, the build fails with the following error:

A problem occurred configuring project ':background_location'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
It appears that the namespace is not specified in the module's build file as required by the latest Android Gradle Plugin (AGP). According to the documentation, the namespace needs to be defined explicitly, starting from AGP version 7.0.0 and onwards. The link provided in the error suggests migrating the package attribute from the AndroidManifest.xml to the build.gradle file.

Since I don't have direct access to the package to apply the fix, and forking the package is not ideal, could you please address this issue in an upcoming release by adding the necessary namespace declaration in the build.gradle file?

Here is the error message in more detail:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':background_location'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
Steps to reproduce:

Add background_location to a Flutter project using the latest Android Gradle Plugin.
Run flutter build apk.
The build fails with the above error.
Environment:

Flutter version: [Your Flutter version]
Android Gradle Plugin: 8.0.0+
Kotlin version: 1.8.22
background_location version: [Latest version]
Thank you in advance for your assistance!

**Comment by abdullah017** [comment]
I get the same error background_location: ^0.13.0

**Comment by kamranbekirovyz** [comment]
> I get the same error background_location: ^0.13.0

Same.

**Comment by korat2511** [comment]
same error with background_location: ^0.13.0


/Users/rutvikkorat/flutter/bin/flutter --no-color build apk

Running Gradle task 'assembleRelease'...                        

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':background_location'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/rutvikkorat/.pub-cache/hosted/pub.dev/background_location-0.13.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 893ms
Running Gradle task 'assembleRelease'...                         1,071ms
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by derGraph** [comment]
I found the solution. In your android/build.gradle add:
`
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}
`
**BEFORE** the other subprojects!
