### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by AnahiRocha** [Almoullim/background_location#220]
I am trying to test the library on Android 14 or higher and I get the following exception:
Unable to create service com.almoullim.background_location.LocationUpdatesService: java.lang.SecurityException: com.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by MoralCode** [comment]
This is likely a duplicate of #150 #214  #200 and theres an open PR that might fix this at #217
