### ISSUE TITLE
Android sleep mode and battery settings unrestricted

### ISSUE THREAD

**Issue by jisu-kroffle** [Almoullim/background_location#228]
I noticed that due to Android's sleep mode, I can't get locations in the background very well.

To address this, we enabled ignoreBattery Optimizations permission and changed the app's battery settings to "no limits."

And it worked

However, I thought that the app should be able to use it without rejecting that permission or proceeding with the settings.

So, I tried to force the battery setting to "limit" and get the background position.

At this time, we found that the app was forcibly shut down within about 20 times.

To solve this problem, what should I share?

**Comment by MoralCode** [comment]
its unlikely that this is something the app has control over. These limits are usually imposed by android - as far as i can tell, most libraries and apps that use background location also require this battery optimization setting be disabled
