### ISSUE TITLE
java.lang.RuntimeException: Unable to create service 

### ISSUE THREAD

**Issue by ITFANDROID** [Almoullim/background_location#232]
Process: com.tofrodriver.tofro_driver, PID: 16016
E/AndroidRuntime(16016): java.lang.RuntimeException: Unable to create service com.almoullim.background_location.LocationUpdatesService: java.lang.SecurityException: com.tofrodriver.tofro_driver: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for 
system broadcasts

Android Version 14

**Comment by MoralCode** [comment]
Please search for existing issues before submitting additional ones. This issue is already filed as #200
