### ISSUE TITLE
On iOS Blue status bar didn't show up while tracking location in the background

### ISSUE THREAD

**Issue by imhafeez** [Almoullim/background_location#29]
I guess you need to set this property on iOS
`locationManager.showsBackgroundLocationIndicator = true
`

**Comment by cormalenv** [comment]
PR pending

**Comment by cormalenv** [comment]
IOS 11+ requires status bar for location updates with permission ‘while in use’. Without as much location updates fail until OS prompts for ‘always’ at some arbitrary period or user manually enters ‘always’ in settings.
