### ISSUE TITLE
Does this code work?

### ISSUE THREAD

**Issue by aronnelson** [Almoullim/background_location#3]
I cannot get it running in the simulator or with my Pixel 3a.
I am running the example app.
It just says waiting...

**Comment by kalismeras61** [comment]
Your project shold be androidx compatible. If yes remove your old app from emulator and try again. Code works well.

**Comment by aronnelson** [comment]
I was running the example app. Both on simulator and Pixel 3a same thing... just says Waiting... Will try again.

**Comment by kalismeras61** [comment]
Understand i tired example app it is working.

**Comment by aronnelson** [comment]
Hmmmmm thank you. I will try again tomorrow. Thanks

**Comment by aronnelson** [comment]
So I tried again with the example file. I give it permission. Then I press Start location service.
I set a breakpoint at:
 BackgroundLocation.getLocationUpdates((location) {
      setState(() {

and it is never called.
However, if I press Get Current location, I do see the location in the Console.

But the main thing I want: BackgroundLocation.getLocationUpdates
is never called. So the app continually says waiting.....

<img width="540" alt="Screen Shot 2019-08-20 at 7 16 48 AM" src="https://user-images.githubusercontent.com/200755/63369713-3eb41280-c31c-11e9-86d7-beb97096bfc6.png">


<img width="366" alt="Screen Shot 2019-08-20 at 7 24 55 AM" src="https://user-images.githubusercontent.com/200755/63369614-03194880-c31c-11e9-8da9-c6b194e0d055.png">

**Comment by aronnelson** [comment]
So just for no reason it just started working. I did nothing different. It started working on my phone and simulator. Has this code been used in a shipping product yet? Kind of worried about it not working, then all of a sudden starting.... Thanks

**Comment by aronnelson** [comment]
OK I did more testing. The project needs to have swift and Kotlin enabled. In addition, the first time it runs in simulator, it will not work despite allowing permissions. You need to quit/kill the app and run again and it will work from then on.

**Comment by Almoullim** [comment]
> the first time it runs in simulator, it will not work despite allowing permissions. You need to quit/kill the app and run again and it will work from then on.

@aronnelson You need to first manually ask for permission before starting the service. You can use [permission_handler](https://pub.dev/packages/permission_handler) for that for now, I will soon, however, integrate the package with this one then reimplement it specifically for this in the future.
