### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by imhafeez** [Almoullim/background_location#30]
cannot receive any location updates on the android. Works fine in iOS

**Comment by imhafeez** [comment]
`/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/ionsd.amspro.q( 5690): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/System  ( 5690): A resource failed to call release.`

**Comment by Almoullim** [comment]
Seems to be related to https://github.com/flutter/flutter/issues/27095

**Comment by gapspt** [comment]
> Seems to be related to [flutter/flutter#27095](https://github.com/flutter/flutter/issues/27095)

The logs can definitely definitely be related to that.

But I wouldn't be so sure that what is causing the logs is the same thing that is causing this issue.
As long as the logs state "allowed" they are just warnings and shouldn't be hindering any functionality.

**Comment by imhafeez** [comment]
But I didn't receive any location update on android. It works well on iOS

**Comment by gapspt** [comment]
I'm sure there is a real issue, I'm just stating that it might not be related to the logs you are seeing.

**Comment by Dixmis** [comment]
Does AndroidManifest.xml contains "<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />" or "<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />" ? Maybe Android didn't ask your permission for location and you can't access it ?

**Comment by imhafeez** [comment]
Thanks @Dixmis I'll check that. and will update here.

**Comment by imhafeez** [comment]
Its working now. 😇. But it took some time while getting first location update.
