### ISSUE TITLE
Get the location updates after each 1 minute? 

### ISSUE THREAD

**Issue by usamamashkoor** [Almoullim/background_location#33]
Hi, I want to create an app like Uber, and I want to get the location updates of the user after each 1 minute even if the app is running in the background is there a way to do this using your library?

I want the solution to work for both Android and Ios.

kindly let me know Thanks.

**Comment by elouiestudent** [comment]
Yes

**Comment by usamamashkoor** [comment]
@elouiestudent can you please share an example or share code so that I can get the idea of how it can be done because this package documentation is not in that much detail.

**Comment by Almoullim** [comment]
@usamamashkoor take a look at the example project https://github.com/Almoullim/background_location/tree/master/example

**Comment by usamamashkoor** [comment]
@Almoullim Thanks, I will check it and will get back to you.
