### ISSUE TITLE
Ask about accuracy

### ISSUE THREAD

**Issue by blackchandelier17** [Almoullim/background_location#35]
Hey, big thanks for this plugin. 

I do notice location class with properties like speed, bearing, accuracy, etc. Because of getting device location isn't always give a real location, sometimes it went far away from my location, so I want to know what is accuracy properties in location class. 
I was able to print it, but it gave me numeric return like 15.656999588012695, 14.217000007629395, etc. But actually I don't understand what it means. The lower its number the more accuracy its location or otherwise, or something else? 
And how can we say that the accuracy is at its best or worst (for example if the accuracy number below 20 can we say that the location is good or not?)

Big Thanks.

**Comment by Almoullim** [comment]
From iOS documentation: 
Accuracy is the radius of uncertainty for the location, measured in meters.

The location’s latitude and longitude identify the center of the circle, and this value indicates the radius of that circle. A negative value indicates that the latitude and longitude are invalid.

---

From Android documentation: 
Accuracy is the estimated horizontal accuracy of this location, radial, in meters

We define horizontal accuracy as the radius of 68% confidence. In other words, if you draw a circle centered at this location's latitude and longitude, and with a radius equal to the accuracy, then there is a 68% probability that the true location is inside the circle.
