### ISSUE TITLE
Doesn't build for iOS due to SWIFT VERSION unstated

### ISSUE THREAD

**Issue by threetins** [Almoullim/background_location#37]
- `background_location` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Any help please

**Comment by threetins** [comment]
Thanks that helped but when I try to execute BackgroundLocation.getPermissions, I get this (see attached)

![Screenshot 2020-07-16 at 12 23 35](https://user-images.githubusercontent.com/17110193/87661249-96434400-c760-11ea-9a08-772e1c44406b.png)

From this:

![Screenshot 2020-07-16 at 12 29 18](https://user-images.githubusercontent.com/17110193/87661274-a22f0600-c760-11ea-97ca-ca79b47a1c14.png)

**Comment by Almoullim** [comment]
Have you added the needed permissions to your app?

**Comment by threetins** [comment]
Where have you described the permissions?

**Comment by threetins** [comment]
Done. Thanks for your help. I added permissions that are described by another plugin called geolocator.
