### ISSUE TITLE
for iOS it stopped after 3 mins.

### ISSUE THREAD

**Issue by joshnavivek** [Almoullim/background_location#4]
Hi, This Plugin for Android is working properly. but for iOS its stopped after 3mins. (Default time for iOS to send App to Sleep). Then updating stopped. please check.

**Comment by Almoullim** [comment]
Should work as expected now. I've tested it for 11 minutes but due to lack of time, I had to attend to other business. I will do further testing when I can.

**Comment by rdev-software** [comment]
Same here...after 3 mins is gone...
Thats not really background location

**Comment by Almoullim** [comment]
> Same here...after 3 mins is gone...
> Thats not really background location
Please make a new issue with more details. As this one has already been resolved.
