### ISSUE TITLE
Slow gps rate

### ISSUE THREAD

**Issue by ikorolev1990** [Almoullim/background_location#40]
BackgroundLocation.startLocationService();
    BackgroundLocation.getLocationUpdates((location) {
      print(DateTime.now().toIso8601String());
    });

I/flutter (25803): 2020-08-05T17:11:17.728799
I/flutter (25803): 2020-08-05T17:11:26.954644
I/flutter (25803): 2020-08-05T17:11:36.168458
I/flutter (25803): 2020-08-05T17:11:45.502994
I/flutter (25803): 2020-08-05T17:11:54.833921
I/flutter (25803): 2020-08-05T17:12:04.750329
I/flutter (25803): 2020-08-05T17:12:15.789310
I/flutter (25803): 2020-08-05T17:12:25.905644
I/flutter (25803): 2020-08-05T17:12:36.014842
I/flutter (25803): 2020-08-05T17:12:45.927024
I/flutter (25803): 2020-08-05T17:12:55.899358
I/flutter (25803): 2020-08-05T17:13:05.995847

Any way to get location faster? Right now it works every 10 seconds, i need 3 seconds

**Comment by Almoullim** [comment]
unfortunately it's not yet supported.

**Comment by ndhbr** [comment]
That is a great pity...

**Comment by Almoullim** [comment]
Closed with #61 thanks to @Sly2024
