### ISSUE TITLE
customize notification message

### ISSUE THREAD

**Issue by piyush303** [Almoullim/background_location#44]
How can I change this message ?

![image](https://user-images.githubusercontent.com/20353112/93000478-591fe600-f546-11ea-9438-e20378b29163.png)

**Comment by sanjog12** [comment]
Open your android module in the android studio then change then the **project view to android view**. Then open LocationUpdatesServices.java file (**background_location > com.almoullim.background_location**) .


```
private val notification: Notification
        get() {
            val intent = Intent(this, LocationUpdatesService::class.java)
            intent.putExtra(EXTRA_STARTED_FROM_NOTIFICATION, true)
            val builder = NotificationCompat.Builder(this)
                    .setContentTitle("Background service is running")
                    .setOngoing(true)
                    .setSound(null)
                    .setPriority(Notification.PRIORITY_HIGH)
                    .setSmallIcon(R.drawable.navigation_empty_icon)
                    .setWhen(System.currentTimeMillis())
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                builder.setChannelId(CHANNEL_ID)
            }
            return builder.build()
        }
```
Then around line number 53, you will see the above function of notification from here u can change this text in the .setContentTitle().

**Comment by Almoullim** [comment]
dup https://github.com/Almoullim/background_location/issues/6
