### ISSUE TITLE
Location service status

### ISSUE THREAD

**Issue by angelschnider** [Almoullim/background_location#47]
Hello,

how is it possible to know if Location Service is enabled with this plugin?
When Location is "stopped" on the device when application is running, the last position remains.
But, I want to "reset" this value but It's not possible to know if BackgroundLocation service was stopped... :-(

Would have you got a workaround about this ask!?

Thanks

**Comment by Almoullim** [comment]
Unfourntly we don't have the option yet. You can keep a local variable and whenever you start the service set it true and when you stop it set it to false.

**Comment by Almoullim** [comment]
dup https://github.com/Almoullim/background_location/issues/10
