### ISSUE TITLE
Do not update on android

### ISSUE THREAD

**Issue by jeanantoine** [Almoullim/background_location#49]
Hi,
I have tested the background_location example with latest flutter (flutter_macos_1.22.1-stable) and Android Studio (4.0.2) on AVD  device (Pixel 3 API 30, Android 10+ 86) and on real Android device.
Manual update works, but no automatic update on both devices.

any help ?

best regards
jg

**Comment by Almoullim** [comment]
Example code is fixed now, thanks.

**Comment by jeanantoine** [comment]
Thank you !
