### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method set_notification_title on channel almoullim.com/background_location))

### ISSUE THREAD

**Issue by smobiledev** [Almoullim/background_location#53]
Versions using: 
background_location: ^0.2.1+1
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.17134.1304], locale en-US)

Am able to run the example provided with plugin source code from github and whenever am trying to integrate this plugin into my app and am getting MissingPluginException as mentioned above. 

Did I miss anything (I followed the steps provided in Readme section) , Can anyone please check whether its working or am the only one getting the issue?

**Comment by Almoullim** [comment]
are you only getting this ios? if yes then can you try not using `BackgroundLocation.setNotificationTitle("Test Title")` on ios, because its for android only. Let me know how it goes.

**Comment by smobiledev** [comment]
I am getting the exception in android itself  and if I comment or didn't use setNotificationTitle method, am getting similar exception for startLocationService method.

Let me check this with updated plug in and let you know.

**Comment by Almoullim** [comment]
Since there's no reply, I'll assume you no longer have this issue.
