### ISSUE TITLE
ios cocoapods issue

### ISSUE THREAD

**Issue by kadnan0900** [Almoullim/background_location#54]
[!] CocoaPods could not find compatible versions for pod "background_location":
  In Podfile:
    background_location (from `.symlinks/plugins/background_location/ios`)

Specs satisfying the `background_location (from `.symlinks/plugins/background_location/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Almoullim** [comment]
Can you try setting your deployment target to 10.0 or higher

**Comment by jozes** [comment]
I had the same problem today. I solved it by commenting out the 2nd line in podfile and replacing it with
platform :ios, '14.0'
Actually it compiled with setting to version 11.0, however on IOS14 it does not work - see another issue from about two weeks ago.
