### ISSUE TITLE
The plugin gets the requests only for few seconds when the app is in background.

### ISSUE THREAD

**Issue by dhruv048** [Almoullim/background_location#56]
The plugin works fine in when the app is in the foreground but when the app goes to background, the plugin gets the location for around 20-30 seconds and then stops getting the location.

Is there anything i have to do to make the plugin get the location till i manually stop it?

Thanks in advance :)

**Comment by bui3itf0ky00** [comment]
Same here !! any help ?

**Comment by NijsTom** [comment]
Same here
