### ISSUE TITLE
background_location: ^0.3.0 not stable

### ISSUE THREAD

**Issue by GautamV234** [Almoullim/background_location#62]
I tried updating my existing package to this new one. It gives me the following error upon running the example app as well as when I run my existing app.

Launching lib\main.dart on ASUS X00TD in debug mode...
 lib\main.dart
Parameter format not correct -
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.2.2+2\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (24, 7): Redeclaration: BackgroundLocationPlugin
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.2.2+2\android\src\main\kotlin\com\almoullim\background_location\LocationUpdatesService.kt: (16, 7): Redeclaration: LocationUpdatesService
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (24, 7): Redeclaration: BackgroundLocationPlugin
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (91, 73): Unresolved reference: NOTIFICATION_MESSAGE

e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (92, 70): Unresolved reference: NOTIFICATION_ICON
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (95, 31): Unresolved reference: updateNotification
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (102, 43): Val cannot be reassigned

e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\BackgroundLocationPlugin.kt: (102, 66): Cannot access 'UPDATE_INTERVAL_IN_MILLISECONDS': it is private in 'Companion'
e: C:\Users\Gautam Vashishtha\flutter\.pub-cache\hosted\pub.dartlang.org\background_location-0.3.0\android\src\main\kotlin\com\almoullim\background_location\LocationUpdatesService.kt: (15, 7): Redeclaration: LocationUpdatesService

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by Almoullim** [comment]
@Sly2024 Can you check this?

**Comment by GautamV234** [comment]
Has this been resolved?

**Comment by dianyulius** [comment]
i had this issue before, i solve it by running `flutter clean` on terminal.
