### ISSUE TITLE
background_location: ^0.2.2  and other versions not working stably in background for Android X.

### ISSUE THREAD

**Issue by GautamV234** [Almoullim/background_location#63]
Hi There, I have used this plugin for a fitness tracking app where I need a continuous data stream of location in the background. However, upon testing, I realized that the stream is not working in the background for higher versions of Android. Please do fix that. Thanks!

**Comment by GautamV234** [comment]
Hi there! Is any work being done on this?

**Comment by cybersokari** [comment]
@GautamV234 What are the versions of Android that you couldn't get streams from?
