### ISSUE TITLE
Unnecessary permission (ACCESS_BACKGROUND_LOCATION) call depending on usage

### ISSUE THREAD

**Issue by bmason8** [Almoullim/background_location#68]
As some of you may know, requesting 'ACCESS_BACKGROUND_LOCATION' now requires that you submit for a special approval before your app is allowed on the the Play Store. This is because that permission is only meant to be used if the app needs background location without the user triggering it or when the app is not on screen (and not showing the user it's using the service). If you want location while the app is not in the foreground or screen is off (like a run tracking app) the 'proper' approach is to start a foreground service. That's what this plugin does, however, it relies on the user having their location permission set to 'All the time'. If it's set to 'While the app is in use' it will only get location a few times an hour.

A clear and concise explanation of these recent platform changes is provided here: (https://medium.com/@adrian.kajda/restrictions-to-background-location-and-foreground-services-in-android-11-9501adcd5795).

So for those of us who want to access frequent 'background location' without needing the 'ACCESS_BACKGROUND_LOCATION' permission and all the baggage that comes with it, there is an issue. But there's a fix! I adjusted 2 lines of code in this plugin and it allows for 'background location' access (technically not in the background because it's a service and showing the user a notification) while the app is not in the foreground.

Both changes occur in the plugins Manifest.xml file:
Change 1: Remove the 'ACCESS_BACKGROUND_LOCATION' permission.
Change 2: Add `'android:foregroundServiceType="location"` to the service tag. Like this:
`<service
            android:name=".LocationUpdatesService"
            android:foregroundServiceType="location"
            android:enabled="true"
            android:exported="true"
            android:permission="" />`

Setting the 'foregroundServiceType' to 'location' is critical. Without it, the system will not realize that the foreground service is meant for location and will therefore greatly limit any attempts to get location info.
Important: In Android 11, you cannot start a foreground service for location in the background so if you use this make sure to start your service before the app is put into the background. If you need that type of functionality, that's what access_background_location is for.

To finish up, I'm not sure if this plugin can be adjusted to allow for both scenarios mentioned above (I suspect not because of the inclusion of the 'ACCESS_BACKGROUND_LOCATION') but I wanted to submit this as an 'issue' just so people are aware. And maybe a better programmer than I am does know how to make it dynamic based on needs. And if not, perhaps it could be duplicated but with those minor changes to cover the 'running app' use case nicely.

And a big thank you to Almoullim for writing this plugin!!! My apologies if this is a totally inappropriate use of submitting an issue!

**Comment by ValentinTaleb** [comment]
Hello @bmason8,
You are totally right. I have been looking for hours for a plugin that take the recent Play Store change into account. But without success.

Do you have a fork with the change you made in the Manifest? So we can use it until @Almoullim finds a way to include it in this plugin?

**Comment by bmason8** [comment]
> Hello @bmason8,
> You are totally right. I have been looking for hours for a plugin that take the recent Play Store change into account. But without success.
> 
> Do you have a fork with the change you made in the Manifest? So we can use it until @Almoullim finds a way to include it in this plugin?

Hey ValentinTaleb,
Unfortunately I haven't been able to figure that out yet (it's something I've never done before and I'm also fairly new to Flutter). I'll be sure to post back here when I get to it.

**Comment by ValentinTaleb** [comment]
Ok. I'll try to do it myself then :)
Thank you

**Comment by bmason8** [comment]
@ValentinTaleb Sorry just saw this now (you tagged the wrong ben haha). I don't totally understand how you added my fork to your pubspec.yaml file. Could you provide a code snippet so I can understand it better? Glad to hear that helped though if it indeed is working.

**Comment by Almoullim** [comment]
Should be solved with this https://github.com/Almoullim/background_location/pull/93?
