### ISSUE TITLE
How to make the service still work when terminating the app?

### ISSUE THREAD

**Issue by 14h4i** [Almoullim/background_location#75]
How to make the service still active when the application is terminated? Until function stopLocationService is called, the service will be terminated.
Thank you,

**Comment by jozes** [comment]
@14h4i  I think the right solution for you would be the one I proposed as feature enhancement and contains all the necessary code. Here is the code: https://github.com/Almoullim/background_location/issues/82

**Comment by Almoullim** [comment]
Sadly, this is not yet supported
