### ISSUE TITLE
Any plan to support Null safety?

### ISSUE THREAD

**Issue by ValentinTaleb** [Almoullim/background_location#84]
Hello,

Thank you very much for this useful package.

Can you tell if you have any plan to support Null safety any time soon?

Thank you advance :)

**Comment by Almoullim** [comment]
Hey, I'm not actively following the latest changes in the flutter world. I'll have to check it and let you know, but if you feel like this feature is needed and you have the time to implement it, I'd be happy to accept a pull request. Thanks :)

**Comment by Almoullim** [comment]
checkout https://github.com/Almoullim/background_location/pull/85
