### ISSUE TITLE
conflict with firebase_messaging plugin

### ISSUE THREAD

**Issue by sd-timaru** [Almoullim/background_location#9]
Hi!
I work on a project where i use the firebase_messaging plugin.
If i add this background_location plugin to the project, when i run the app i receive this error:

E/AndroidRuntime( 9189): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 9189): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
E/AndroidRuntime( 9189): 	at android.app.ActivityThread.access$1300(ActivityThread.java:199)
E/AndroidRuntime( 9189): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
E/AndroidRuntime( 9189): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9189): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9189): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 9189): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9189): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9189): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 9189): Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 9189): 	at com.almoullim.background_location.BackgroundLocationPlugin$Companion.registerWith(BackgroundLocationPlugin.kt:37)
E/AndroidRuntime( 9189): 	at com.almoullim.background_location.BackgroundLocationPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime( 9189): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
E/AndroidRuntime( 9189): 	at com.example.my_background_location.Application.registerWith(Application.java:18)
E/AndroidRuntime( 9189): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/AndroidRuntime( 9189): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime( 9189): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)

Steps to reproduce:

1. create new flutter project with Java support

2. add to pubspec.yaml:

  firebase_messaging: ^5.1.6
  background_location:
    path: ../background_location-master

3. follow Android installation instructions from here: https://pub.dev/packages/firebase_messaging#-readme-tab-

4. run the app

**Comment by Almoullim** [comment]
Should be fixed with https://github.com/Almoullim/background_location/pull/13. Re-open if not.

**Comment by hussenIbrahim** [comment]
using firebase message ^7.0.3 and  background location: ^0.4.0
when background location is running and then  close app the notification is received but stopping the background location and then close the app and then push a notification it show app keeps stopping and no notification is showing

**Comment by hussenIbrahim** [comment]
> using firebase message ^7.0.3 and background location: ^0.4.0
> when background location is running and then close app the notification is received but stopping the background location and then close the app and then push a notification it show app keeps stopping and no notification is showing

solved after repair  cache
Thanks

**Comment by temirfe** [comment]
repair cache didn't help, it's not working if project has a FirebaseMessaging.onBackgroundMessage
