### ISSUE TITLE
[RFC] Removing permission_handler

### ISSUE THREAD

**Issue by Almoullim** [Almoullim/background_location#91]
Due to a lot of issues with `permission_handler` like this one https://github.com/Almoullim/background_location/issues/87 and many others, I think removing the package and letting the developer handle requesting permission from their end might be a better and more flexible solution.

with this, both
```dart
BackgroundLocation.getPermissions()
```
and 
```dart
BackgroundLocation.checkPermissions()
```
will be removed.

Any ideas or whether or not you think this is a good solution?

**Comment by RolBakMous** [comment]
Hi Almoullim,
Sounds good to me! Do you have a timeline, when this is going to be fixed?
Thanks for the awesome package!

**Comment by NijsTom** [comment]
Hey Almoullim,

Will this remove the need for the permission_handler dependency?
