### ISSUE TITLE
Because background_location depends on background_location, version solving failed.

### ISSUE THREAD

**Issue by MuhammadSufyanMalik** [Almoullim/background_location#94]
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (3 weeks ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

Why  am I facing this issue ?
Any Idea ?
Thanks

**Comment by DevTiago** [comment]
Are you testing in a real device or on a simulator?
I've facing the same kind of error but on another package... 

Which SDK version do you have on your app/build.gradle?

**Comment by MuhammadSufyanMalik** [comment]
Didn't receive any support yet.
