### ISSUE TITLE
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: almoullim.com/background_location. Response ID: 0

### ISSUE THREAD

**Issue by savassuphan** [Almoullim/background_location#99]
Hello everyone, I am getting the following error, does anyone know the reason and solution?

Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: almoullim.com/background_location. Response ID: 0

**Comment by Almoullim** [comment]
Can you try using version 0.6.0 and see if you still get the error. Just wanna see if its caused by the last update.

**Comment by pflee2002** [comment]
This is a repeatable issue. I tried 0.6.0 and 0.6.1. The same error was reported. Please help fixed.

**Comment by pflee2002** [comment]
The problematic function is the streamsubscription. The listen() does not work. 

      _bg_geolocationSubscritption = BackgroundLocation()
          .getCurrentLocation()
          .asStream()
          .listen((Location position)......

**Comment by MoralCode** [comment]
this appears to be a duplicate of https://github.com/Almoullim/background_location/issues/25
